# SPDX-License-Identifier: GPL-2.0-only
ccflags-y := -I $(src)/../qat_common
obj-$(CONFIG_CRYPTO_DEV_QAT_LCE) += qat_lce.o
qat_lce-objs := adf_drv.o adf_lce_hw_data.o adf_lce_isr.o adf_lce_ring.o adf_lce_comp.o
